### ISSUE TITLE
16 letters nick ranks don't working

### ISSUE THREAD

**Issue by kukubaczek** [john01dav/SQLPermsIssues#22]
If player has a 16 letters nick the permissions don't work.

**Comment by kukubaczek** [comment]
[17:50:17 ERROR]: Could not pass event PlayerJoinEvent to SQLPerms v2.2.3
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigot.jar:git-Spigot-1.7.9-R0.2-205-g0a049fa]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-Spigot-1.7.9-R0.2-205-g0a049fa]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:509) [spigot.jar:git-Spigot-1.7.9-R0.2-205-g0a049fa]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:494) [spigot.jar:git-Spigot-1.7.9-R0.2-205-g0a049fa]
        at net.minecraft.server.v1_7_R4.PlayerList.c(PlayerList.java:265) [spigot.jar:git-Spigot-1.7.9-R0.2-205-g0a049fa]
        at net.minecraft.server.v1_7_R4.PlayerList.a(PlayerList.java:152) [spigot.jar:git-Spigot-1.7.9-R0.2-205-g0a049fa]
        at net.minecraft.server.v1_7_R4.LoginListener.c(LoginListener.java:119) [spigot.jar:git-Spigot-1.7.9-R0.2-205-g0a049fa]
        at net.minecraft.server.v1_7_R4.LoginListener.a(LoginListener.java:44) [spigot.jar:git-Spigot-1.7.9-R0.2-205-g0a049fa]
        at net.minecraft.server.v1_7_R4.NetworkManager.a(NetworkManager.java:189) [spigot.jar:git-Spigot-1.7.9-R0.2-205-g0a049fa]
        at net.minecraft.server.v1_7_R4.ServerConnection.c(ServerConnection.java:81) [spigot.jar:git-Spigot-1.7.9-R0.2-205-g0a049fa]
        at net.minecraft.server.v1_7_R4.MinecraftServer.v(MinecraftServer.java:734) [spigot.jar:git-Spigot-1.7.9-R0.2-205-g0a049fa]
        at net.minecraft.server.v1_7_R4.DedicatedServer.v(DedicatedServer.java:289) [spigot.jar:git-Spigot-1.7.9-R0.2-205-g0a049fa]
        at net.minecraft.server.v1_7_R4.MinecraftServer.u(MinecraftServer.java:584) [spigot.jar:git-Spigot-1.7.9-R0.2-205-g0a049fa]
        at net.minecraft.server.v1_7_R4.MinecraftServer.run(MinecraftServer.java:490) [spigot.jar:git-Spigot-1.7.9-R0.2-205-g0a049fa]
        at net.minecraft.server.v1_7_R4.ThreadServerApplication.run(SourceFile:628) [spigot.jar:git-Spigot-1.7.9-R0.2-205-g0a049fa]
Caused by: java.lang.IllegalArgumentException: Player list names can only be a maximum of 16 characters long
        at org.bukkit.craftbukkit.v1_7_R4.entity.CraftPlayer.setPlayerListName(CraftPlayer.java:194) ~[spigot.jar:git-Spigot-1.7.9-R0.2-205-g0a049fa]
        at src.john01dav.sqlperms.permissions.PlayerPermissionManager.reloadPermissions(PlayerPermissionManager.java:52) ~[?:?]
        at src.john01dav.sqlperms.permissions.PermissionsListener.playerJoinEvent(PermissionsListener.java:42) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.7.0_79]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) ~[?:1.7.0_79]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.7.0_79]
        at java.lang.reflect.Method.invoke(Method.java:606) ~[?:1.7.0_79]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:298) ~[spigot.jar:git-Spigot-1.7.9-R0.2-205-g0a049fa]
        ... 14 more

**Comment by john01dav** [comment]
What do you mean "nick"? Please include detailed steps to reproduce this error and place the errors in either codetags or a pastebin like website.

**Comment by kukubaczek** [comment]
If my nickname is example: "TheFallingCookie" (16 letters) the plugin don't
working corectly. When I'm joining to server in console I se errors, and
ranks don't set.

2015-06-01 18:02 GMT+02:00 john01dav <notifications@github.com>:

**Comment by john01dav** [comment]
Is this on a default configuration? If not, try it with the default configuration.

**Comment by kukubaczek** [comment]
This is a config:
http://pastebin.com/Aatc8ZJe



2015-06-01 18:35 GMT+02:00 john01dav <notifications@github.com>:

**Comment by john01dav** [comment]
That's not a config.yml, it's a permissions.yml. You also didn't follow my instructions to try it on a fresh server.

**Comment by kukubaczek** [comment]
I'm using default server. On a fresh server this same problem.

**Comment by john01dav** [comment]
Ok. I don't have any accounts of 16 in length. Could you send me a PM on Spigot with a temporary password for one of your high length accounts so I can test my fix? Feel free to change the password back when you're done. If you don't want to do this, I understand, but it will take a lot longer for me to find a fix.

**Comment by john01dav** [comment]
Fixed in 2.3.0.
